<?php

/**
 * @file
 * Contains forcontu_pec2.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function forcontu_pec2_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the forcontu_pec2 module.
    case 'help.page.forcontu_pec2':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module Forcontu Pec 2') . '</p>';
      return $output;

    default:
  }
}
